[package]
name = "librypt-aead-aes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
librypt-aead = { version = "0.1", git = "https://github.com/librypt/librypt-aead" }

